### ISSUE TITLE
Unicode non-breaking spaces affect HTML line wrapping

### ISSUE THREAD

**Issue by davidjb** [ITatJCU/itatjcu.github.io#2]
There's a number of unicode non-breaking space characters in the `index.html` file that affect how the lines in the presenters table are displayed.  They're impossible to see without searching for a copy of the character (and copying a nbsp character from a web browser appears to copy a regular ascii space).

Turns out Vim has an option to show nbsp characters like so:

```
set listchars+=nbsp:·
```

and enable list mode if not already on with `set list`.  Now, these characters will show up as dots (well, interpuncts, but whatever) so they can be stomped.  

(Adding as a GitHub issue as link bait for the next person who hits the same issue out there)

**Comment by davidjb** [comment]
Discussed and solved together with @lindsaymarkward -- I'll be adjusting my vim configuration and burning this into my brain for next time.

**Comment by lindsaymarkward** [comment]
PHPStorm identifies these spaces differently when you search for them (but still displays both as spaces):
![screen shot 2015-06-17 at 12 10 55 pm](https://cloud.githubusercontent.com/assets/7665042/8198857/03bf9318-14f0-11e5-89a3-bb35ea6f17c3.png)
